from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_BRONZE_DIR = ROOT / "data" / "streaming" / "bronze" / "yellow" / "2025-08"
DEFAULT_OUTPUT = ROOT / "docs" / "data_quality_metrics.yaml"


KEY_COLUMNS = [
    "VendorID",
    "tpep_pickup_datetime",
    "tpep_dropoff_datetime",
    "PULocationID",
    "DOLocationID",
    "trip_distance",
    "fare_amount",
    "total_amount",
]


def _is_present(value: object) -> bool:
    return value is not None and value != ""


def _is_non_negative_number(value: object) -> bool:
    return isinstance(value, (int, float)) and value >= 0


def _parse_timestamp(value: object) -> datetime | None:
    if not isinstance(value, str) or not value:
        return None
    try:
        return datetime.fromisoformat(value)
    except ValueError:
        return None


def _format_percent(numerator: int, denominator: int) -> float:
    if denominator == 0:
        return 0.0
    return round((numerator / denominator) * 100, 2)


def _yaml_value(value: object) -> str:
    if isinstance(value, str):
        escaped = value.replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(value, bool):
        return str(value).lower()
    return str(value)


def _write_metrics_yaml(metrics: list[dict[str, object]], output_path: Path) -> None:
    output_path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by scripts/calculate_data_quality.py",
        "data_quality_metrics:",
    ]
    for metric in metrics:
        lines.append(f"  - name: {_yaml_value(metric['name'])}")
        for key, value in metric.items():
            if key == "name":
                continue
            lines.append(f"    {key}: {_yaml_value(value)}")
    output_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def calculate_metrics(bronze_dir: Path) -> list[dict[str, object]]:
    files = sorted(bronze_dir.glob("*.jsonl"))
    if not files:
        raise FileNotFoundError(f"No JSONL batch files found in {bronze_dir}")

    row_count = 0
    complete_key_rows = 0
    valid_amount_rows = 0
    valid_location_rows = 0
    valid_pickup_month_rows = 0
    latest_file_update = max(path.stat().st_mtime for path in files)

    for path in files:
        with path.open("r", encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue

                row = json.loads(line)
                row_count += 1

                if all(_is_present(row.get(column)) for column in KEY_COLUMNS):
                    complete_key_rows += 1

                if (
                    _is_non_negative_number(row.get("trip_distance"))
                    and _is_non_negative_number(row.get("fare_amount"))
                    and _is_non_negative_number(row.get("total_amount"))
                ):
                    valid_amount_rows += 1

                pickup_location = row.get("PULocationID")
                dropoff_location = row.get("DOLocationID")
                if (
                    isinstance(pickup_location, int)
                    and 1 <= pickup_location <= 265
                    and isinstance(dropoff_location, int)
                    and 1 <= dropoff_location <= 265
                ):
                    valid_location_rows += 1

                pickup_time = _parse_timestamp(row.get("tpep_pickup_datetime"))
                if pickup_time is not None and pickup_time.strftime("%Y-%m") == "2025-08":
                    valid_pickup_month_rows += 1

    generated_at = datetime.now(timezone.utc).isoformat(timespec="seconds")
    last_update = datetime.fromtimestamp(latest_file_update, timezone.utc).isoformat(
        timespec="seconds"
    )

    return [
        {
            "name": "Row count",
            "definition": "Number of records written to the bronze data product for yellow taxi 2025-08.",
            "current_value": row_count,
            "expected_threshold": ">= 3,500,000",
            "update_cadence": "Every pipeline run",
            "status": "pass" if row_count >= 3_500_000 else "fail",
        },
        {
            "name": "Completeness of key columns",
            "definition": "Percentage of rows where VendorID, pickup/dropoff timestamps, pickup/dropoff locations, trip_distance, fare_amount, and total_amount are non-null.",
            "current_value": f"{_format_percent(complete_key_rows, row_count)}%",
            "expected_threshold": ">= 99%",
            "update_cadence": "Every pipeline run",
            "status": "pass" if _format_percent(complete_key_rows, row_count) >= 99 else "fail",
        },
        {
            "name": "Validity of amount and distance values",
            "definition": "Percentage of rows where trip_distance, fare_amount, and total_amount are numeric and non-negative.",
            "current_value": f"{_format_percent(valid_amount_rows, row_count)}%",
            "expected_threshold": ">= 90%",
            "update_cadence": "Every pipeline run",
            "status": "pass" if _format_percent(valid_amount_rows, row_count) >= 90 else "fail",
        },
        {
            "name": "Validity of taxi zone IDs",
            "definition": "Percentage of rows where PULocationID and DOLocationID are integers in the TLC taxi zone range 1-265.",
            "current_value": f"{_format_percent(valid_location_rows, row_count)}%",
            "expected_threshold": ">= 99%",
            "update_cadence": "Every pipeline run",
            "status": "pass" if _format_percent(valid_location_rows, row_count) >= 99 else "fail",
        },
        {
            "name": "Pickup month consistency",
            "definition": "Percentage of rows where tpep_pickup_datetime belongs to the published product month 2025-08.",
            "current_value": f"{_format_percent(valid_pickup_month_rows, row_count)}%",
            "expected_threshold": ">= 99%",
            "update_cadence": "Every pipeline run",
            "status": "pass" if _format_percent(valid_pickup_month_rows, row_count) >= 99 else "fail",
        },
        {
            "name": "Data freshness",
            "definition": "UTC timestamp of the most recently updated bronze batch file.",
            "current_value": last_update,
            "expected_threshold": "Updated after each successful streaming run",
            "update_cadence": "Every pipeline run",
            "status": "informational",
        },
        {
            "name": "Metrics generated at",
            "definition": "UTC timestamp when this data quality report was generated.",
            "current_value": generated_at,
            "expected_threshold": "N/A",
            "update_cadence": "Manually or every pipeline run",
            "status": "informational",
        },
    ]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Calculate data quality metrics for the bronze product")
    parser.add_argument("--bronze-dir", type=Path, default=DEFAULT_BRONZE_DIR)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--write", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    metrics = calculate_metrics(args.bronze_dir)
    if args.write:
        _write_metrics_yaml(metrics, args.output)
        print(f"wrote {args.output}")
    else:
        for metric in metrics:
            print(f"{metric['name']}: {metric['current_value']} ({metric['status']})")


if __name__ == "__main__":
    main()
